#!/bin/sh
#cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# remove surface
#rm -rf 0 > /dev/null 2>&1
#rm -f ./flange ./*.obj > /dev/null 2>&1
rm -rf constant/extendedFeatureEdgeMesh > /dev/null 2>&1
rm -f constant/triSurface/water.eMesh > /dev/null 2>&1
rm -f constant/polyMesh/boundary
\rm -f 0/pointLevel > /dev/null 2>&1
\rm -f 0/cellLevel > /dev/null 2>&1

cleanCase

# ----------------------------------------------------------------- end-of-file
