#!/bin/sh

cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Copy initial conditions
cp -rf 0.org 0

runApplication blockMesh
runApplication surfaceFeatureExtract


if [ "$1" = "-parallel" ]
    then
    nProc=$(getNumberOfProcessors)
    runApplication decomposePar
    runParallel snappyHexMesh $nProc -overwrite
    runParallel createPatch $nProc -overwrite
    ls -d processor* | xargs -I {} rm -rf ./{}/0
    ls -d processor* | xargs -I {} cp -r 0.org ./{}/0
    runParallel $(getApplication) $nProc
    runApplication reconstructParMesh -constant
    runApplication reconstructPar -latestTime
else
    runApplication snappyHexMesh -overwrite
    runApplication createPatch -overwrite
    runApplication $(getApplication)
fi

# runApplication $(getApplication)
